### ISSUE TITLE
+noclip bug that allows for super speed teleport

### ISSUE THREAD

**Issue by karlbonitz** [jonitaikaponi/ckSurf#15]
10:11 PM - ashm0re: well it's like this
10:11 PM - ashm0re: I binded a key to +noclip
10:12 PM - ashm0re: and when I hold it down, I can noclip right
10:12 PM - ashm0re: well if I fly through the air, and let go of the key while I'm still inside the start zone
10:12 PM - ashm0re: when I fly OUT with my speed from noclipping
10:12 PM - ashm0re: it starts my timer
10:12 PM - ashm0re: ONLY works with the zones for telehopping though
10:13 PM - ashm0re: it's apparently how a ton of servers have their WRs
10:13 PM - ashm0re: I was able to pretty much beat any record on that other server by doing it

Found an interesting bug within noclipping on servers. I have tested this multiple times and it works. It's essentially the same as using !noclip as admin within a server, and flying out of the start zone really fast.

Many people on my servers have beat the world records because of this bug / glitch. Is there any possible way to fix this? Maybe a var to check and make sure the player is out of noclip and not moving before enabling the timer?

Thanks again!

**Comment by jonitaikaponi** [comment]
Are you running an old version of ckSurf? This was already fixed here two weeks ago: https://forums.alliedmods.net/showpost.php?p=2318955&postcount=130.

Even if you are running an old version, I just made a few adjustments to it now so that it's a bit more aggressive than before.

**Comment by karlbonitz** [comment]
Joni,

Thanks a ton for this fix! I'm going to give it a shot tonight when I can upload it to the server. I was running a fairly up to date version of ckSurf, but still experienced the issue. I'll keep you posted within a few hours.

**Comment by karlbonitz** [comment]
Joni, 
I apologize for the late response, I uploaded the new cfSurf plugin as of 8/2/2015 and the bug still exists in the speed start zones. I can record a video if need be. using +noclip and keeping the button depressed while noclipping and letting go after leaving the zone allows the player to fly through with no decrease in speed.

**Comment by jonitaikaponi** [comment]
Even if a player would manage that, their timer should stop after 5 seconds now.

I did notice a bug in the code though. It should teleport players back to the start if they used noclip recently now.

**Comment by karlbonitz** [comment]
Everything from what I can tell seems to be working perfect after that fix a few minutes ago! Thank you for doing this!
